### ISSUE TITLE
Indicate the default value of an option

### ISSUE THREAD

**Issue by EchoPouet** [flibby-jibbit/clive#1]
First of all, thank you for your module, it's very good.

Can you indicate the default values in the help file for your next version ?

Also, are you planning to add your project to [VPM](https://vpm.vlang.io/) ?

Thank you very much.

**Comment by flibby-jibbit** [comment]
Hi @EchoPouet . If you request help for the argument, the default is displayed. See https://github.com/flibby-jibbit/clive/blob/9434998a0a99315eae2cdd074214c7e0d37876dd/help.v#L64 The command line would look like

```bash
$ app-name command-name help arg-name
```

It's been a while, but I think that's right.

 I am not planning on adding the project to VPM as I actually don't use Vlang anymore. I had to pivot away from it at work, and I don't like to use too many languages at once, so I'm coding mainly in Golang right now. I need to update the README to indicate that I'm no longer updating this repository.
